language: bash
services: docker

install:
- git clone https://github.com/greenlogles/nagios-ha.git ~/nagios-ha

env:
  - COMPONENT=nagios-server
  - COMPONENT=gearman-server
  - COMPONENT=gearman-worker

before_script:
  - env | sort
  - cd "$COMPONENT"
  - image="nagios-ha:${COMPONENT}"
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
