version: '3'
services:
  gearman-server:
    image: "greenlogles/nagios-ha:gearman-server"
    build:
      context: ./gearman-server/
    ports:
     - "4730:4730"
  gearman-worker01:
    image: "greenlogles/nagios-ha:gearman-worker"
    depends_on:
     - gearman-server
    build:
      context: ./gearman-worker/
    environment:
     - GEARMAN_SERVERS=gearman-server
     - DEBUG=true
  nagios-server:
    image: "greenlogles/nagios-ha:nagios-server"
    depends_on:
     - gearman-server
    build:
      context: ./nagios-server/
    environment:
     - GEARMAN_SERVERS=gearman-server
    volumes:
     - /docker/var:/opt/nagios/var
#     - /docker/etc/nagios.cfg:/opt/nagios/etc/nagios.cfg
  nagios-ui:
    image: "greenlogles/nagios-ha:nagios-ui"
    depends_on:
     - nagios-server
    ports:
     - "8080:80"
    volumes:
     - /docker/var:/opt/nagios/var
     - /docker/etc:/opt/nagios/etc
